---
# This playbook deploys the whole application stack in this site.  

- name: apply common configuration to all nodes
  hosts: all
  remote_user: vagrant
  sudo: true

  roles:
    - httpd
    - mariadb
    - php55-remi
    - phpmyadmin-remi
    - php-project
    - git
