---
# This playbook deploys the whole application stack in this site.  

- name: apply common configuration to all nodes
  hosts: all
  remote_user: vagrant
  sudo: yes

  roles:
    - git
    - httpd
    - mariadb
    - php-remi
    - phpmyadmin-remi
    - php-project
    - php-tools
